name: KingdomsOfArden-AntiCombatLog
main: net.kingdomsofarden.andrew2060.anticombatlog.AntiCombatLogPlugin
load: POSTWORLD
version: 20-RC
depend: [Heroes]
softdepend: [BattleArena, BattleTracker]
description: Provides Heroes Compatible Anti-Combat Log Capabilities
permissions:
  combatlog.bypass.*:
    description: Allows for bypassing all combatlog checks
    children:
      combatlog.bypass.logoff: true
      combatlog.bypass.command: true
      combatlog.bypass.teleport: true
  combatlog.bypass.logoff:
    description: Allows for logging off without triggering combat log
  combatlog.bypass.command:
    description: Allows for using commands in combat
  combatlog.bypass.teleport:
    description: Allows for teleporting in combat