name: Swagserv-AntiCombatLog
main: net.swagserv.andrew2060.anticombatlog.AntiCombatLogPlugin
load: POSTWORLD
version: 2.00
depend: [Heroes, BattleArena, BattleTracker]
description: Provides Heroes Compatible Anti-Combat Log Capabilities
 